test: husky pre-commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -4,7 +4,12 @@ set -e
 # Run the lint command
 echo ""
 echo "\033[0;31mRunning lint command...\033[0m"
-npm run lint || { echo "\033[0;31mLinting failed. Commit aborted.\033[0m"; exit 1; }
+npm run lint || {
+  echo "\n\033[0;31m--------------------------------------------------------------------------------\033[0m"
+  echo "\033[0;31mLinting failed. Commit aborted.\033[0m"
+  echo "\033[0;31m--------------------------------------------------------------------------------\033[0m\n"
+  exit 1;
+}
 
 # Run the format command
 # echo ""
